// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7CRUDr9xmz_D4IsM9haV9czC_uVc7kB0',
    appId: '1:992101639315:web:867596eb22b0c51fb39966',
    messagingSenderId: '992101639315',
    projectId: 'studyapp-ab877',
    authDomain: 'studyapp-ab877.firebaseapp.com',
    storageBucket: 'studyapp-ab877.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGfmTUVeqcN8DZX8wb_MoV_jxp3LoUtw0',
    appId: '1:992101639315:android:66f59b6bcb809f74b39966',
    messagingSenderId: '992101639315',
    projectId: 'studyapp-ab877',
    storageBucket: 'studyapp-ab877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6X0asV5Y8au39HrSrHieBkv2VJsik9cU',
    appId: '1:992101639315:ios:8bf566211b72def6b39966',
    messagingSenderId: '992101639315',
    projectId: 'studyapp-ab877',
    storageBucket: 'studyapp-ab877.appspot.com',
    iosClientId: '992101639315-l5l02h7pfe4ns4uh26mo66nnsr568d5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6X0asV5Y8au39HrSrHieBkv2VJsik9cU',
    appId: '1:992101639315:ios:8bf566211b72def6b39966',
    messagingSenderId: '992101639315',
    projectId: 'studyapp-ab877',
    storageBucket: 'studyapp-ab877.appspot.com',
    iosClientId: '992101639315-l5l02h7pfe4ns4uh26mo66nnsr568d5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tm',
  );
}
